#basic
dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorflow"
project_name: "XuanCe_Benchmark"
logger: "tensorboard"  # Choices: "tensorboard", "wandb".
wandb_user_name: "your_user_name"

render: True
render_mode: None # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
test_steps: 2000
learner: "DQN_Learner"
device: "cuda:0"
env_seed: 1
distributed_training: False





agent: "DQN"
env_name: "Classic Control"
env_id: "CartPole-v1"
vectorize: "DummyVecEnv"
policy: "BasicHyper_Q_network"
representation: "KAN"
runner: "DRL"

render: True # Whether to render the environment when testing.
render_mode: "human" # Choices: 'human', 'rgb_array'.
device: "cuda:0"  # Choose an calculating device.
representation_hidden_size: [512,1024,]
representation_block_type: ['M','M']
representation_kan_configId: [0,]
representation_kan_grid_sizeValue: [5,]
representation_kan_spline_order_Value: [3,]

q_hidden_size: [512,]
q_block_type: ['M','M']
q_hidden_kan_configId: [1,]
q_hidden_kan_grid_sizeValue: [5,]
q_hidden_kan_spline_order_Value: [3,]

spline_order: 3

activationMLP: 'relu'
activationKAN: 'relu'
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 500000
batch_size: 1024
learning_rate: 0.001
gamma: 0.99

start_greedy: 1
end_greedy: 0.01
decay_step_greedy: 400000
sync_frequency: 50
training_frequency: 1
running_steps: 500000  # 200k
start_training: 1000

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 20000
test_episode: 1
log_dir: "./logs/dqn/MLP"
model_dir: "./models/dqn/MLP"
